name: primeiro-pipeline
on:
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  primeiro-job:
    name: "Meu Primeiro Job"
    runs-on: ubuntu-latest
    steps:
      - name: "Minha primeira ação"
        run: echo "Xibara ximamoto"
      - name: "Segunda ação"
        run: |
          echo "Workflow criado"
          echo "parabéns"
  segundo-job:
    name: "Instalação do NodeJs"
    runs-on: ubuntu-latest
    needs: [primeiro-job]
    steps:
      - name: "Verificação do versão do nodeJS"
        run: node --version
      - name: "Definição da versão do node"
        uses: actions/setup-node@v4
        with:
          node-version: '20.13.1'            
      - name: "Verificação do versão do nodeJS"
        run: node --version 
