name: primeiro-pipeline
on:
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  primeiro-job:
    name: "Meu Primeiro Job"
    runs-on: ubuntu-latest
    steps:
      - name: "Minha primeira ação"
        run: echo "Xibara ximamoto"
      - name: "Segunda ação"
        run: |
          echo "Workflow criado"
          echo "parabéns"
  segundo-job:
    name: "Instalação do NodeJs"
    runs-on: ubuntu-latest
    steps:
      - name: "Verificação do versão do nodeJS"
        run: node --version        
  
